FROM tensorflow_cpu:latest
LABEL maintainer="Erwan BERNARD https://github.com/edmBernard/DockerFiles"

RUN apt-get update && \
    apt-get install -y \
    openmpi-bin \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# CNTK
RUN pip3 install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.5.1-cp35-cp35m-linux_x86_64.whl

# Set CNTK backend for Keras
ENV KERAS_BACKEND=cntk

CMD ["/bin/bash"]
