FROM ubuntu:16.04
MAINTAINER Erwan BERNARD

# Pick up some dependencies
RUN apt-get update && apt-get install -y \
        build-essential cmake git nano vim \
        curl wget rsync unzip \
        libboost-all-dev \
        pkg-config \
        libfreetype6-dev \
        libpng-dev \
        libzmq3-dev \
        libavutil-dev \
        libjpeg-dev \
        libjpeg8-dev \
        libtiff-dev \
        libjasper-dev \
        libgtk2.0-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libv4l-dev \
        libatlas-base-dev \
        python \
        python-dev \
        python-numpy \
        python-scipy \
        python3 \
        python3-dev \
        python3-numpy \
        python3-scipy \
        python-setuptools
RUN apt-get install -y software-properties-common && \
    add-apt-repository ppa:jonathonf/python-3.6 && \
    apt-get update && \
    apt-get install -y python3.6 python3.6-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install pip for python2 and 3
RUN wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate && \
    python get-pip.py && \
    python3 get-pip.py && \
    python3.6 get-pip.py && \
    rm get-pip.py

# install python2 tools
RUN pip2 --no-cache-dir install \
        numpy \
        ipython \
        ipykernel \
        jupyter \
        matplotlib \
        scipy \
        scikit-image \
        docopt \
        path.py \
        bokeh \
        line_profiler \
        && \
    python2 -m ipykernel install

# install python3 tools
RUN pip3.6 --no-cache-dir install \
        numpy \
        jupyter \
        ipython \
        matplotlib \
        scipy \
        docopt \
        path.py \
        bokeh \
        line_profiler \
        && \
    python3.6 -m ipykernel install

RUN ldconfig

# OPENCV
RUN pip2 --no-cache-dir install opencv-python && \
    pip3.6 --no-cache-dir install opencv-python

# NUMBA

# install numba (JIT compiler for python)
# current version are llvm-3.8, clang-3.8, llvmlite-0.14.0, numba-0.29
RUN apt-get update && \
    apt-get install -y llvm clang && \
    pip2 install llvmlite numba && \
    pip3 install llvmlite numba && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# configuration
RUN mkdir /home/dev
WORKDIR /home/dev/host
ENV HOME /home/dev
# RUN useradd dev && chown -R dev: /home/dev
# USER dev

# configure bash
RUN ln -snf /bin/bash /bin/sh
RUN echo 'force_color_prompt=yes' >> /home/dev/.bashrc && \
    cat /root/.bashrc >> /home/dev/.bashrc && \
    echo 'PS1="\[\033[31;1m\]$BOX_NAME\[\033[00m\] $PS1" ' >> /home/dev/.bashrc

RUN echo "alias python='/usr/bin/python3.6'" >> /home/dev/.bashrc
RUN echo "alias python3='/usr/bin/python3.6'" >> /home/dev/.bashrc

CMD ["/bin/bash"]
