FROM alpine:edge
MAINTAINER Erwan BERNARD

RUN apk update && apk --no-cache add \
        linux-headers \
        nano wget \
        gcc \
        make \
        musl-dev \
        tar \
        python3 \
        py-numpy

# install redis
RUN cd /root && \
        wget http://download.redis.io/redis-stable.tar.gz && \
        tar xvzf redis-stable.tar.gz && \
        rm redis-stable.tar.gz

RUN cd /root/redis-stable && \
        make

# install pip for python3
RUN wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate && \
    python3 get-pip.py && \
    rm get-pip.py

RUN pip3.6 --no-cache-dir install \
        docopt \
        schema \
        path.py \
        redis

WORKDIR /root

# don't forget --login to have file load at start
# eg. sudo docker run --rm -it alpine-python3.6 /bin/sh --login
RUN echo "PS1='\[\033[1;36m\]alpine\[\033[00m\] \[\033[34m\]\u@\h\[\033[00m\]:\[\033[36m\]\w\[\033[00m\]$ '" > /etc/profile.d/shrc.sh
