FROM alpine:adge
MAINTAINER Erwan BERNARD

RUN apk update && apk --no-cache add \
        nano wget \
        python3

# install pip for python3
RUN wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate && \
    python3 get-pip.py && \
    rm get-pip.py

RUN pip3.6 --no-cache-dir install \
        numpy \
        matplotlib \
        scipy \
        docopt \
        schema \
        path.py \
        redis \
        line_profiler \
        jupyter \
        ipython \
        && \
    python3 -m ipykernel install
