FROM redis_cpu:latest
MAINTAINER Erwan BERNARD

ENV CHAINER_DIR "$LIB_DIR/chainer"

# Clone chainer repo
RUN cd "$LIB_DIR" && git clone https://github.com/chainer/chainer.git

# Install chainer package
RUN cd "$CHAINER_DIR" && python2 setup.py install
RUN cd "$CHAINER_DIR" && python3 setup.py install
