FROM redis_gpu:latest
LABEL maintainer="Erwan BERNARD https://github.com/edmBernard/DockerFiles"

# install python3 tools
RUN pip3 --no-cache-dir install -U \
    pandas \
    sklearn \
    h5py \
    onnx protobuf

# tensorflow 2.6 support cuda 11.2 and cudnn 8.1 : https://www.tensorflow.org/install/source#linux
RUN pip3 --no-cache-dir install tensorflow-gpu

CMD ["/bin/bash"]
