FROM redis_gpu:latest
LABEL maintainer="Erwan BERNARD https://github.com/edmBernard/DockerFiles"

# install python3 tools
RUN pip3 --no-cache-dir install -U \
    pandas \
    sklearn \
    h5py \
    onnx protobuf

# tensorflow 2.0 does not support cuda 10.1 but only cuda 10.0 : https://www.tensorflow.org/install/source#linux
RUN pip3 --no-cache-dir install tensorflow-gpu

CMD ["/bin/bash"]
