FROM redis_cpu:latest
LABEL maintainer="Erwan BERNARD https://github.com/edmBernard/DockerFiles"

# install python3 tools
RUN pip3 --no-cache-dir install -U \
    pandas \
    sklearn \
    h5py \
    onnx protobuf

RUN pip3 --no-cache-dir install tensorflow

CMD ["/bin/bash"]
